#####===run1.mac for serious runs===
###=====G4State_PreInit=====
/control/verbose 0
/run/verbose 0
/run/numberOfThreads 8

###ChR_project
###++++++++++++++++++++++++++++++++

###check overLap while building geometry
#/ChR_project/DetectorConsturction/checkOverlap true

###divide radiator into layers
#/ChR_project/DetectorConsturction/noOfRadLayers 1

###change verbose
#/ChR_project/DetectorConsturction/verboseLevel 0

###rotate radiator (in deg by default)
#/ChR_project/DetectorConsturction/radiatorAngle 22.0

###change radiator half-thickness (in um by default)
#/ChR_project/DetectorConsturction/radiatorThickness 100

###change radiator material (G4_SILICON_DIOXIDE for electrons and Diamond for GenericIons)
#/ChR_project/DetectorConsturction/radiatorMaterial Diamond

###change detector radius (in um by default)
#/ChR_project/DetectorConsturction/detectorRadius 35

###change detector angle, relative to the radiator center (in deg by default)
#/ChR_project/DetectorConsturction/detectorAngle 59.5

###change detector distance, relative to the radiator center (in cm)
#/ChR_project/DetectorConsturction/detectorDistance 37.6

###change default cuts flag - by default it is true
#/ChR_project/PhysicsList/useNonDefaultCuts false

###change gamma-cut value (in um by default)
#/ChR_project/PhysicsList/gammaRangeCut

###change electron-cut value (in um by default)
#/ChR_project/PhysicsList/electronRangeCut

###change positron-cut value (in um by default)
#/ChR_project/PhysicsList/positronRangeCut

###change proton-cut value (in um by default)
#/ChR_project/PhysicsList/protonRangeCut

###select one of the available EM physics constructors
### 0 - for "G4EmStandardPhysics"; 1 - for "G4EmStandardPhysics_option1"; 2 - for "G4EmStandardPhysics_option2";
### 3 - for "G4EmStandardPhysics_option3"; 4 - for "G4EmStandardPhysics_option4"; 5 - for "G4EmLivermorePhysics";
### 6 - for "G4EmLowEPPhysics"; 7 - for "G4EmPenelopePhysics"; 8 - for "G4EmStandardPhysicsGS";
### 9 - for "G4EmStandardPhysicsSS" 10 - for "G4EmStandardPhysicsWVI"
#/ChR_project/PhysicsList/selectEmPhysics 0
###++++++++++++++++++++++++++++++++

###=====G4State_Init=====
/run/initialize

###=====G4State_Idle=====

###ChR_project
###++++++++++++++++++++++++++++++++
###Print about the C++ process and all registered Cherenkov models
#/ChR_project/ChRProcess/dumpInfo

###Print about what Cherenkov process is
#/ChR_project/ChRProcess/processDescription

###allow models to include change in energy (the conservation law)
#/ChR_project/BaseChR_Model/useEnergyLossInModels true

###change number of beta steps for building physics tables
#/ChR_project/BaseChR_Model/noOfBetaSteps 20

###change verbose
#/ChR_project/BaseChR_Model/changeModelVerbose 0

###print built physics tables
#/ChR_project/BaseChR_Model/printBaseChRPhysicsVector

###change verbose level of MyOpticalParameters and G4OpticalParameters
#/ChR_project/OpticalParameters/verboseLevel 0

###change Gaussian sigma of the beam, 0 for pencil-like (in um by default)
#/ChR_project/PrimaryGenerator/beamSigma 0

###change Gaussian sigma error (G_sigma +- err_G_sigma) (in um by default)
#/ChR_project/PrimaryGenerator/beamSigmaError 0

###change Gaussian sigma for the beam divergence (in mrad by default)
#/ChR_project/PrimaryGenerator/divergenceSigma

###change primary-particle energy (full energy for e-, and energy per nucleon for GenericIons) (in MeV by default)
#/ChR_project/PrimaryGenerator/particleEnergy 855

###change number of fired primaries per event (for this project E9 events with 10 particles)
/ChR_project/PrimaryGenerator/noOfPrimaryParticles 10

###used to change massNo of primaries (for GenericIons - only works if atomicNo != 0 as well... otherwise e-)
#/ChR_project/PrimaryGenerator/massNo 0

###used to change atomicNo of primaries (for GenericIons - only works if massNo != 0 as well... otherwise e-)
#/ChR_project/PrimaryGenerator/atomicNo 0

###used to change SteppingAction verbose level
#/ChR_project/SteppingAction/verboseLevel 0
###++++++++++++++++++++++++++++++++

###=====G4State_GeomClosed && G4State_EventProc=====
/run/beamOn 1000000000